/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.yewton.testmmdiktat.app

import net.yewton.testmmdiktat.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
